spring:
  config:
    activate:
      on-profile: "redisdev"

  redis:
    host: localhost
    port: 6379
    password:
    ttls:
      user-info: 3_600_600
      reservation: 30000
#     reservation: 86400000
      point: 7_200_000
      heart: 7_200_000