spring:
  config:
    activate:
      on-profile: "mail"

  mail:
    host: smtp.gmail.com
    port: 587
    username: pi3.14stepup
    password: nbrnfqketihdxhhc
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true