spring:
  profiles:
    group:
      release:
        - jwt
        - mail
        - springdoc
        - redisrelease
        - mongorelease
      develop:
        - jwt
        - mail
        - springdoc
        - redisdev
        - mongodev
    # release(prod) / develop(dev) 중에 선택
    active: release
