spring:
  profiles:
    group:
      release:
        - jwt
        - mail
        - springdoc
      develop:
        - jwt
        - mail
        - springdoc
    # release(prod) / develop(dev) 중에 선택
    active: develop
