server:
  port: 8080

spring:
  config:
    activate:
      on-profile: "develop"

  initDb:
    enable: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/stepup;mode=mysql
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  com.pi.stepup: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace