spring:
  profiles:
    group:
      release:
        - jwt
        - mail
        - springdoc
        - redisrelease
        - mongorelease
      develop:
        - jwt
        - mail
        - springdoc
        - redisdev
        - mongodev

    active: release
