spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/stepup
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  secret: XUrYUhZfrEWLtykR7h80CrcITM59YLt5CRi3AdqZu33

logging.level:
  com.pi.stepup: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6